name=input("enter the name:")
print(len(name))
print(name.isupper())
print(name.islower())
print(name.isalpha())
print(name.isdigit())
print(name.isnumeric())
print(name.upper())
print(name.lower())
print(name.title())
print(name.swapcase())
print(name.strip())
print(name.replace('a', 'z'))
print(name.split())
print(name.split('a'))
